---
title: "Publications"
---

- **MacFadyen, AC**; Paterson, GK. (2024). Methicillin resistance in Staphylococcus pseudintermedius encoded within novel staphylococcal cassette chromosome mec (SCCmec) variants. 2024, dkae096. doi: 10.1093/jac/dkae096
- McSorley, JC, **MacFadyen, AC**; Kerr, L; Tucker, NP. (2022). Host lysolipid differentially modulates virulence factor expression and antimicrobial susceptibility in Pseudomonas aeruginosa. Microbiology, 2022, 168(7). doi: 10.1099/mic.0.001179.
- Pickering, AC; Yebra, G; Xiangyu, G; Goncheva, MI; Wee, BA; **MacFadyen, AC**; Muehlbauer, LF; Alves, J; Cartwright, RA; Paterson, GK; Fitzgerald, RJ. (2021).  Evolutionary and Functional Analysis of Coagulase Positivity among the Staphylococci. mSphere, 2021 Aug 25;6(4):e0038121. doi: 10.1128/mSphere.00381-21
- **MacFadyen, AC**; Leroy, S; Harrison, EM; Parkhill, J; Holmes, M; Paterson, GK. (2019). Staphylococcus pseudoxylosus sp. nov., isolated from bovine mastitis. International Journal of Systematic and Evolutionary Microbiology, doi: 10.1099/ijsem.0.003416
- **MacFadyen, AC**; Harrison, EM; Morgan, FJE; Parkhill, J; Holmes, MA; Paterson, GK. (2019).  A mecC allotype, mecC3, in the CoNS Staphylococcus caeli, encoded within a variant SCCmecC. Journal of Antimicrobial Chemotherapy. 1;74(3):547-552. doi: 10.1093/jac/dky502
- **MacFadyen, AC**; Walker, A; Paterson, GK. (2019). Streptococcus hillyeri sp. nov., isolated from an equine tracheal sample. International Journal of Systematic and Evolutionary Microbiology. doi: 10.1099/ijsem.0.003489
- **MacFadyen, AC**; Fisher, E; Costa, B; Cullen, C; Paterson, G. (2018).  Genomic epidemiology of methicillin-resistant Macrococcus caseolyticus from dairy cattle bulk tank milk in England and Wales. Microbial Genomics. 2018, Aug;4(8). doi: 10.1099/mgen.0.000191
- **MacFadyen, AC**; Harrison, EM; Ellington, MJ; Parkhill¬, J; Holmes, MA; Paterson¬, GK. (2018) A highly conserved mecC encoding SCCmec type XI in a bovine isolate of methicillin-resistant Staphylococcus xylosus. Journal of Antimicrobial Chemotherapy. 2018, Aug 27. doi: 10.1093/jac/dky333
- **MacFadyen, AC**; Drigo, I; Harrison, EM; Parkhill, J; Holmes; Paterson, GK. (2018).  Staphylococcus caeli sp. nov., isolated from air sampling in an industrial rabbit holding. International Journal of Systematic and Evolutionary Microbiology. Int J Syst Evol Microbiol. 2018 Nov 14. doi: 10.1099/ijsem.0.003098
- Beaton, A; Lood, C;  Cunningham-Oakes, E; **MacFadyen, A**; Mullins, Alex; El Bestawy, W; Botelho, J; Chevalier, S; Coleman, S; Dalzell, C; Dolan, S; Faccenda, A; Ghequire, M; Higgins, S; Kutschera, A; Murray, J; Redway, M; Salih, T; da Silva, A; Smith, B; Smits, N; Thomson, R; Woodcock, S; Welch, M; Cornelis, P; Lavigne, R; van Noort, V; Tucker, N. (2018). Community-led comparative genomic and phenotypic analysis of the aquaculture pathogen Pseudomonas baetica a390T sequenced by Ion semiconductor and Nanopore technologies, FEMS Microbiology Letters.  doi: 10.1093/femsle/fny069 
- Pethick, F. E., **MacFadyen, AC**, Tang, Z., Sangal, V., Liu, T.-T., Chu, J., Kosec, G., Petkovic, H., Guo, M., Kirby, R., Hoskisson, P.A., Herron, P.R., Hunter, I. S. (2013). Draft genome sequence of the oxytetracycline-producing bacterium Streptomyces rimosus ATCC 10970. Genome Announcements, 1(2). doi: 10.1128/genomea.00063-13
